/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Controlador.*;
import java.awt.Image;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Luis Ahumada
 */
public class GMant extends javax.swing.JFrame {

public static final String AGREGAR_INT="tickets";
public static final String AGREGAR_EXT="registroInc";
    
    
    
    public GMant() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Gestion Mantenimiento");
    }
    public Image getIconImage(){
    Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenes/icono.png"));
    return retValue;
    }
    
    public void ejecutar(){
     setVisible(true);
     jTableExt.setEnabled(false);
     jTableInt.setEnabled(false);
    
    }
        public void setControlador(Controlador control){
            
        jButtonInt.setActionCommand(AGREGAR_INT);
        jButtonExt.setActionCommand(AGREGAR_EXT);
        jButtonInt.addActionListener(control);
        jButtonExt.addActionListener(control);
    }
        
         public void cargarTablaInt(ArrayList lista){
        
        DefaultTableModel tabla = new DefaultTableModel();
        tabla.addColumn("Codigo");
        tabla.addColumn("Lugar");
        tabla.addColumn("Tipo");
        tabla.addColumn("Fallo");
        tabla.addColumn("Solucion");
        tabla.addColumn("Fecha");
        tabla.addColumn("Estado");
        
        for(int i=0; i<lista.size();i++){
            tabla.addRow((Object[]) lista.get(i));
        }
        jTableInt.setModel(tabla);        
    }   
            public void cargarTablaExt(ArrayList lista){
        
        DefaultTableModel tabla = new DefaultTableModel();
        tabla.addColumn("Número");
        tabla.addColumn("Lugar");
        tabla.addColumn("Tipo");
        tabla.addColumn("Fallo");
        tabla.addColumn("Solucion");
        tabla.addColumn("Fecha");
        tabla.addColumn("Estado");
        
        for(int i=0; i<lista.size();i++){
            tabla.addRow((Object[]) lista.get(i));
        }
        jTableExt.setModel(tabla);        
    }        
        
        
        
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExt = new javax.swing.JButton();
        jButtonInt = new javax.swing.JButton();
        jLabelExt = new javax.swing.JLabel();
        jScrollPaneInt = new javax.swing.JScrollPane();
        jTableInt = new javax.swing.JTable();
        jScrollPaneExt = new javax.swing.JScrollPane();
        jTableExt = new javax.swing.JTable();
        jLabelInt = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 204, 0));
        setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        setIconImage(getIconImage());
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 1920, 1080));
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonExt.setBackground(new java.awt.Color(0, 0, 204));
        jButtonExt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonExt.setForeground(new java.awt.Color(255, 255, 255));
        jButtonExt.setText("Agregar Incidencia externa");
        jButtonExt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExtActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonExt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 250, 30));

        jButtonInt.setBackground(new java.awt.Color(0, 0, 204));
        jButtonInt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButtonInt.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInt.setText("Agregar Incidencia interna");
        jButtonInt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIntActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 220, 30));

        jLabelExt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelExt.setForeground(new java.awt.Color(255, 255, 255));
        jLabelExt.setText("INCIDENCIAS EXTERNAS");
        getContentPane().add(jLabelExt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jTableInt.setBackground(new java.awt.Color(204, 204, 204));
        jTableInt.setBorder(new javax.swing.border.MatteBorder(null));
        jTableInt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTableInt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Codigo", "Lugar", "Tipo", "Fallo", "Solucion", "Fecha", "Estado"
            }
        ));
        jTableInt.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jTableInt.setAutoscrolls(false);
        jTableInt.setColumnSelectionAllowed(true);
        jTableInt.setGridColor(new java.awt.Color(0, 0, 0));
        jTableInt.setRowHeight(30);
        jTableInt.setRowSelectionAllowed(false);
        jScrollPaneInt.setViewportView(jTableInt);

        getContentPane().add(jScrollPaneInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 1220, 260));

        jTableExt.setBackground(new java.awt.Color(204, 204, 204));
        jTableExt.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTableExt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Numero", "Lugar", "Tipo", "Fallo", "Solucion", "Fecha", "Estado"
            }
        ));
        jTableExt.setGridColor(new java.awt.Color(0, 0, 0));
        jTableExt.setName(""); // NOI18N
        jTableExt.setRowHeight(30);
        jScrollPaneExt.setViewportView(jTableExt);

        getContentPane().add(jScrollPaneExt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 1220, 260));

        jLabelInt.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabelInt.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInt.setText("INCIDENCIAS INTERNAS");
        getContentPane().add(jLabelInt, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo - Gestores.png"))); // NOI18N
        jLabelFondo.setMaximumSize(new java.awt.Dimension(1920, 1080));
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExtActionPerformed
      
    }//GEN-LAST:event_jButtonExtActionPerformed

    private void jButtonIntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIntActionPerformed
    
    }//GEN-LAST:event_jButtonIntActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonExt;
    private javax.swing.JButton jButtonInt;
    private javax.swing.JLabel jLabelExt;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelInt;
    private javax.swing.JScrollPane jScrollPaneExt;
    private javax.swing.JScrollPane jScrollPaneInt;
    private javax.swing.JTable jTableExt;
    private javax.swing.JTable jTableInt;
    // End of variables declaration//GEN-END:variables
}
